controllerManager:
  extraRules:
  - apiGroups:
    - security.openshift.io
    resourceNames:
    - anyuid
    resources:
    - securitycontextconstraints
    verbs:
    - use

upgradeCRDs:
  extraRules:
  - apiGroups:
    - security.openshift.io
    resourceNames:
    - anyuid
    resources:
    - securitycontextconstraints
    verbs:
    - use

postInstall:
  labelNamespace: false
    extraRules:
    - apiGroups:
      - security.openshift.io
      resourceNames:
      - anyuid
      resources:
      - securitycontextconstraints
      verbs:
      - use

enableRuntimeDefaultSeccompProfile: false
