controllerManager:
  extraRules:
  - apiGroups:
    - security.openshift.io
    resourceNames:
    - nonroot-v2
    resources:
    - securitycontextconstraints
    verbs:
    - use

upgradeCRDs:
  extraRules:
  - apiGroups:
    - security.openshift.io
    resourceNames:
    - nonroot-v2
    resources:
    - securitycontextconstraints
    verbs:
    - use

postInstall:
  labelNamespace: 
    extraRules:
    - apiGroups:
      - security.openshift.io
      resourceNames:
      - nonroot-v2
      resources:
      - securitycontextconstraints
      verbs:
      - use

enableRuntimeDefaultSeccompProfile: false
