apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: openshift-gitops
spec:
  source:
    repoURL: https://github.com/ch-stark/argocdhelmgatekeeper
    targetRevision: main
    path: values
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
