apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
spec:
  source:
    repoURL: https://github.com/ch-stark/argocdhelmgatekeeper
    targetRevision: main
    path: .
    kustomize:
      enableHelm: true   # This appends --enable-helm to the kustomize build command
